<a href="https://colab.research.google.com/github/KaustubhSN12/deep_learning_exercise/blob/main/DL_1_eigen_values_vector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1_d matrix
import numpy as np

m =np.array([[1,2],[2,3]])

print("printing the original square array\n",m)
print()

w,v=np.linalg.eig(m)

print("printing Right eigen values of the given square array:\n",w)
print()
print("Printing Right Eigen vectors of the given square array:\n",v)

printing the original square array
 [[1 2]
 [2 3]]

printing Right eigen values of the given square array:
 [-0.23606798  4.23606798]

Printing Right Eigen vectors of the given square array:
 [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


In [ ]:
#2_d matrix
import numpy as np

m =np.array([[1, 2, 3],[2, 3, 4],[4, 5, 6]])

print("printing the original square array\n",m)
print()

w,v=np.linalg.eig(m)

print("printing Right eigen values of the given square array:\n",w)
print()
print("Printing Right Eigen vectors of the given square array:\n",v)

printing the original square array
 [[1 2 3]
 [2 3 4]
 [4 5 6]]

printing Right eigen values of the given square array:
 [ 1.08309519e+01 -8.30951895e-01  1.01486082e-16]

Printing Right Eigen vectors of the given square array:
 [[ 0.34416959  0.72770285  0.40824829]
 [ 0.49532111  0.27580256 -0.81649658]
 [ 0.79762415 -0.62799801  0.40824829]]


In [ ]:
#5*5 matrix
import numpy as np

m =np.array([[1, 2, 3,4,5],[2, 3, 4,5,6],[4, 5, 6,7,8],[7, 3, 6,5,6],[3, 5, 6,8,8]])

print("printing the original square array\n",m)
print()

w,v=np.linalg.eig(m)

print("printing Right eigen values of the given square array:\n",w)
print()
print("Printing Right Eigen vectors of the given square array:\n",v)

printing the original square array
 [[1 2 3 4 5]
 [2 3 4 5 6]
 [4 5 6 7 8]
 [7 3 6 5 6]
 [3 5 6 8 8]]

printing Right eigen values of the given square array:
 [ 2.56371437e+01+0.j         -1.34005114e+00+0.96344573j
 -1.34005114e+00-0.96344573j  4.29586019e-02+0.j
  2.26432038e-15+0.j        ]

Printing Right Eigen vectors of the given square array:
 [[-2.79081661e-01+0.j          2.29886112e-01-0.1947117j
   2.29886112e-01+0.1947117j  -3.40768251e-01+0.j
   3.42997170e-01+0.j        ]
 [-3.64047588e-01+0.j          1.37555368e-01-0.14215074j
   1.37555368e-01+0.14215074j  5.36638946e-02+0.j
  -3.01250974e-15+0.j        ]
 [-5.33979442e-01+0.j         -4.71061208e-02-0.03702881j
  -4.71061208e-02+0.03702881j  8.42528187e-01+0.j
  -8.57492926e-01+0.j        ]
 [-4.60133456e-01+0.j         -7.52091904e-01+0.j
  -7.52091904e-01-0.j         -3.83614856e-01+0.j
   3.42997170e-01+0.j        ]
 [-5.41041531e-01+0.j          5.04844828e-01+0.21450121j
   5.04844828e-01-0.21450121j -1.54864720e

In [ ]:
#using tensorflow
import tensorflow as tf

e_matrix_A=tf.random.uniform([2,2],minval=3,maxval=10,dtype=tf.float32,name="matrixA")
print("matrix A: \n{}\n\n".format(e_matrix_A))

eigen_values_A,eigen_vectors_A=tf.linalg.eigh(e_matrix_A)
print("Eigen Vectors: \n{} \n\nEigen Values: \n{}\n".format(eigen_vectors_A, eigen_values_A))

matrix A: 
[[5.065995  7.1020064]
 [4.974819  9.174273 ]]


Eigen Vectors: 
[[-0.8311596  -0.55603397]
 [ 0.55603397 -0.8311596 ]] 

Eigen Values: 
[ 1.7379125 12.502357 ]



In [ ]:
#using tensorflow
import tensorflow as tf

e_matrix_A=tf.random.uniform([3,3],minval=3,maxval=10,dtype=tf.float32,name="matrixA")
print("matrix A: \n{}\n\n".format(e_matrix_A))

eigen_values_A,eigen_vectors_A=tf.linalg.eigh(e_matrix_A)
print("Eigen Vectors: \n{} \n\nEigen Values: \n{}\n".format(eigen_vectors_A, eigen_values_A))

matrix A: 
[[8.482036  8.480813  7.662485 ]
 [3.9450166 6.796668  3.4064429]
 [3.4335814 6.567756  4.360069 ]]


Eigen Vectors: 
[[ 0.0156073  -0.81825835  0.5746387 ]
 [ 0.6345944   0.45223075  0.6267194 ]
 [-0.7726878   0.35488114  0.5263203 ]] 

Eigen Values: 
[-1.1032643  4.8125706 15.929466 ]



In [ ]:
#using tensorflow
import tensorflow as tf

e_matrix_A=tf.random.uniform([5,5],minval=3,maxval=10,dtype=tf.float32,name="matrixA")
print("matrix A: \n{}\n\n".format(e_matrix_A))

eigen_values_A,eigen_vectors_A=tf.linalg.eigh(e_matrix_A)
print("Eigen Vectors: \n{} \n\nEigen Values: \n{}\n".format(eigen_vectors_A, eigen_values_A))

matrix A: 
[[5.952142  7.986307  4.130282  7.5313745 9.845405 ]
 [5.649968  7.764248  7.1825237 8.697939  7.124213 ]
 [9.613327  4.88843   7.2458305 6.282888  3.2717001]
 [8.285719  7.3766003 9.074878  4.036797  6.0447927]
 [8.252368  4.648823  8.185345  4.195083  3.2842538]]


Eigen Vectors: 
[[ 0.36408088  0.7477889   0.10639842 -0.23029993  0.49386054]
 [ 0.21657583 -0.13597167  0.24240188  0.8504629   0.39059055]
 [ 0.4069516  -0.6058811  -0.28050196 -0.3556808   0.5119655 ]
 [-0.6205345   0.14727059 -0.61368036  0.15489991  0.43892038]
 [-0.51948786 -0.18314789  0.68893814 -0.27050388  0.38572145]] 

Eigen Values: 
[-5.838572  -3.2535696 -0.8750786  4.054741  34.195755 ]

